version: "3.7"
services:
  broker:
    image: eclipse-mosquitto
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  device1:
    build:
      context: .
      dockerfile: device.Dockerfile
    volumes:
      - ./configs/device1.json:/etc/mqtt-device/config.json
    network_mode: service:broker

