version: "3.7"
services:
  broker:
    image: eclipse-mosquitto
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - 9001:9001

  lamp1:
    build:
      context: .
      dockerfile: device.Dockerfile
    volumes:
      - ./configs/device1.json:/etc/mqtt-device/config.json:ro
      # - ./mqtt-device/:/mqtt-device/app:ro
    depends_on:
      - broker

  ac1:
    build:
      context: .
      dockerfile: device.Dockerfile
    volumes:
      - ./configs/device2.json:/etc/mqtt-device/config.json:ro
      # - ./mqtt-device/:/mqtt-device/app:ro
    depends_on:
      - broker

  fan1:
    build:
      context: .
      dockerfile: device.Dockerfile
    volumes:
      - ./configs/device3.json:/etc/mqtt-device/config.json:ro
      # - ./mqtt-device/:/mqtt-device/app:ro
    depends_on:
      - broker

  lamp2ct:
    build:
      context: .
      dockerfile: device.Dockerfile
    volumes:
      - ./configs/device4.json:/etc/mqtt-device/config.json:ro
      # - ./mqtt-device/:/mqtt-device/app:ro
    depends_on:
      - broker

  portal:
    build:
      context: .
      dockerfile: portal.Dockerfile
    ports:
      - 8080:8080
